# Generated by Codex on 2025-12-26

from django.db import migrations


def copy_wagtail_images(apps, schema_editor):
    OldImage = apps.get_model("wagtailimages", "Image")
    NewImage = apps.get_model("core", "CustomImage")

    if NewImage.objects.exists():
        return

    new_images = []
    for old in OldImage.objects.all():
        new_images.append(
            NewImage(
                id=old.id,
                title=old.title,
                description=old.description,
                file=old.file.name,
                width=old.width,
                height=old.height,
                created_at=old.created_at,
                uploaded_by_user_id=old.uploaded_by_user_id,
                collection_id=old.collection_id,
                focal_point_x=old.focal_point_x,
                focal_point_y=old.focal_point_y,
                focal_point_width=old.focal_point_width,
                focal_point_height=old.focal_point_height,
                file_size=old.file_size,
                file_hash=old.file_hash,
            )
        )

    if new_images:
        NewImage.objects.bulk_create(new_images, batch_size=200)

    ContentType = apps.get_model("contenttypes", "ContentType")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    old_ct = ContentType.objects.get(app_label="wagtailimages", model="image")
    new_ct, _ = ContentType.objects.get_or_create(
        app_label="core",
        model="customimage",
    )
    TaggedItem.objects.filter(content_type=old_ct).update(content_type=new_ct)


def reverse_copy_wagtail_images(apps, schema_editor):
    NewImage = apps.get_model("core", "CustomImage")
    NewImage.objects.all().delete()

    ContentType = apps.get_model("contenttypes", "ContentType")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    old_ct = ContentType.objects.get(app_label="wagtailimages", model="image")
    try:
        new_ct = ContentType.objects.get(app_label="core", model="customimage")
    except ContentType.DoesNotExist:
        return
    TaggedItem.objects.filter(content_type=new_ct).update(content_type=old_ct)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(copy_wagtail_images, reverse_copy_wagtail_images),
    ]
