# Generated by Codex on 2025-12-26

from django.db import migrations
from django.db.models import Q
from PIL import Image, ImageOps


def backfill_dimensions(apps, schema_editor):
    ImageModel = apps.get_model("core", "CustomImage")
    for image in ImageModel.objects.filter(Q(width__isnull=True) | Q(height__isnull=True)):
        if not image.file:
            continue
        try:
            image.file.open("rb")
            pil_image = Image.open(image.file)
            pil_image = ImageOps.exif_transpose(pil_image)
            width, height = pil_image.size
            image.file.close()
        except Exception:
            try:
                image.file.close()
            except Exception:
                pass
            continue
        image.width = width
        image.height = height
        image.save(update_fields=["width", "height"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_copy_wagtail_images"),
    ]

    operations = [
        migrations.RunPython(backfill_dimensions, migrations.RunPython.noop),
    ]
