# Generated by Django 5.2.9 on 2025-12-26 13:02

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE accounts_user
            SET bio = '[]'
            WHERE bio IS NULL OR btrim(bio) = '';
            UPDATE accounts_user
            SET bio = json_build_array(
                json_build_object('type', 'paragraph', 'value', bio)
            )::text
            WHERE bio IS NOT NULL
              AND btrim(bio) <> ''
              AND bio NOT LIKE '[%';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
