# Generated by Django 5.2.9 on 2025-12-26 13:45

from django.db import migrations, models
from django.utils.text import slugify


def populate_author_slug(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    existing = set(
        User.objects.exclude(author_slug__isnull=True)
        .exclude(author_slug="")
        .values_list("author_slug", flat=True)
    )
    for user in User.objects.filter(author_slug__isnull=True) | User.objects.filter(author_slug=""):
        first_name = getattr(user, "first_name", "") or ""
        last_name = getattr(user, "last_name", "") or ""
        full_name = f"{first_name} {last_name}".strip()
        base = slugify(full_name) or slugify(user.username or "") or "user"
        slug = base
        suffix = 2
        while slug in existing or User.objects.filter(author_slug=slug).exclude(pk=user.pk).exists():
            slug = f"{base}-{suffix}"
            suffix += 1
        user.author_slug = slug
        user.save(update_fields=["author_slug"])
        existing.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author_slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(populate_author_slug, migrations.RunPython.noop),
    ]
