# Generated by Django 5.2.9 on 2025-12-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_authors_delete_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated reading time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
