# Generated by Django 5.2.9 on 2025-12-23 23:25

from django.db import migrations


def add_missing_blogindexpages(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")
    BlogIndexPage = apps.get_model("blog", "BlogIndexPage")

    try:
        blog_index_ct = ContentType.objects.get(
            app_label="blog",
            model="blogindexpage",
        )
    except ContentType.DoesNotExist:
        return

    missing_pages = (
        Page.objects.filter(content_type=blog_index_ct)
        .exclude(pk__in=BlogIndexPage.objects.values_list("pk", flat=True))
    )

    table_name = BlogIndexPage._meta.db_table
    for page in missing_pages.iterator():
        # Insert the child-table row without triggering Wagtail Page validation.
        schema_editor.execute(
            f"INSERT INTO {table_name} (page_ptr_id, intro) VALUES (%s, %s)",
            [page.pk, ""],
        )


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogindexpage"),
    ]

    operations = [
        migrations.RunPython(add_missing_blogindexpages, noop),
    ]
