# Generated by Django 5.2.9 on 2025-12-23 22:34

import json

import wagtail.fields
from django.db import migrations


def convert_blogpage_body_to_json(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    table_name = BlogPage._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT page_ptr_id, body FROM {table_name}")
        rows = cursor.fetchall()

    for page_id, body in rows:
        if not body:
            continue
        try:
            parsed = json.loads(body)
            if isinstance(parsed, list):
                continue
        except (TypeError, ValueError):
            pass

        stream_value = json.dumps([{"type": "paragraph", "value": body}])
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"UPDATE {table_name} SET body = %s WHERE page_ptr_id = %s",
                [stream_value, page_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_backfill_blogindexpage'),
    ]

    operations = [
        migrations.RunPython(convert_blogpage_body_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
