# Generated by Django 5.2.9 on 2025-12-27 02:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show_toc',
            field=models.BooleanField(default=True, help_text='Show table of contents on the post page.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic']}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
