# Generated by Django 5.2.9 on 2025-12-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogpage_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPage",
            new_name="BlogPost",
        ),
    ]
