# Generated by Django 5.2.9 on 2025-12-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_blogpage_to_blogpost"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogIndexPage",
            new_name="BlogPage",
        ),
    ]
