# Generated by Django 5.2.9 on 2025-12-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_show_toc_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='auto_reading_time',
            field=models.BooleanField(default=True, help_text='Calculate reading time automatically.'),
        ),
    ]
