# Generated by Django 5.2.9 on 2025-12-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='intro',
        ),
    ]
