# Generated by Django 5.2.9 on 2025-12-26 17:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('home', '0002_blankpage'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE home_aboutpage
            SET intro = '[]'
            WHERE intro IS NULL OR btrim(intro) = '';
            UPDATE home_aboutpage
            SET intro = json_build_array(
                json_build_object('type', 'paragraph', 'value', intro)
            )::text
            WHERE intro IS NOT NULL
              AND btrim(intro) <> ''
              AND intro NOT LIKE '[%';

            UPDATE home_aboutpage
            SET body = '[]'
            WHERE body IS NULL OR btrim(body) = '';
            UPDATE home_aboutpage
            SET body = json_build_array(
                json_build_object('type', 'paragraph', 'value', body)
            )::text
            WHERE body IS NOT NULL
              AND btrim(body) <> ''
              AND body NOT LIKE '[%';

            UPDATE home_blankpage
            SET intro = '[]'
            WHERE intro IS NULL OR btrim(intro) = '';
            UPDATE home_blankpage
            SET intro = json_build_array(
                json_build_object('type', 'paragraph', 'value', intro)
            )::text
            WHERE intro IS NOT NULL
              AND btrim(intro) <> ''
              AND intro NOT LIKE '[%';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='blankpage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
