# Generated by Django 5.2.9 on 2025-12-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_publictransportpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublicTransportPage",
        ),
    ]
