# Generated by Django 5.2.9 on 2025-12-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aboutpage_body_alter_aboutpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='reading_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated reading time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blankpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blankpage',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blankpage',
            name='reading_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated reading time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='blankpage',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
