# Generated by Django 5.2.9 on 2025-12-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0010_linepage_station_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportstation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transportstation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
