# Generated by Django 5.2.9 on 2025-12-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0011_alter_transportstation_created_at_and_more'),
        ('public_transport', '0011_publictransportstationpage'),
    ]

    operations = [
    ]
