# Generated by Django 5.2.9 on 2025-12-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0012_merge_20251226_0239'),
        ('public_transport', '0012_stationpage_parent_line_display'),
    ]

    operations = [
    ]
