# Generated by Django 5.2.9 on 2025-12-24 22:20

from django.db import migrations


def create_initial_poi_data(apps, schema_editor):
    POICategory = apps.get_model("poi", "POICategory")
    POIFeature = apps.get_model("poi", "POIFeature")

    categories = [
        ("Restaurant", "restaurant"),
        ("Cafe", "cafe"),
        ("Bar", "bar"),
        ("Temple", "temple"),
        ("Market", "market"),
        ("Viewpoint", "viewpoint"),
        ("Hotel", "hotel"),
        ("BTS / MRT Station", "bts-mrt-station"),
    ]

    for title, slug in categories:
        POICategory.objects.get_or_create(title=title, slug=slug)

    features = [
        ("WiFi", "wifi", "Amenities"),
        ("Vegan options", "vegan-options", "Food"),
        ("Rooftop", "rooftop", "Atmosphere"),
        ("Air conditioning", "air-conditioning", "Amenities"),
        ("Cash only", "cash-only", "Payment"),
        ("Wheelchair accessible", "wheelchair-accessible", "Accessibility"),
    ]

    for title, slug, group in features:
        POIFeature.objects.get_or_create(title=title, slug=slug, group=group)


def remove_initial_poi_data(apps, schema_editor):
    POICategory = apps.get_model("poi", "POICategory")
    POIFeature = apps.get_model("poi", "POIFeature")
    POICategory.objects.filter(
        slug__in=[
            "restaurant",
            "cafe",
            "bar",
            "temple",
            "market",
            "viewpoint",
            "hotel",
            "bts-mrt-station",
        ]
    ).delete()
    POIFeature.objects.filter(
        slug__in=[
            "wifi",
            "vegan-options",
            "rooftop",
            "air-conditioning",
            "cash-only",
            "wheelchair-accessible",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("poi", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_poi_data, remove_initial_poi_data),
    ]
