# Generated by Django 5.2.9 on 2025-12-24 22:51

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_initial_poi_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poipagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='poi.poipage'),
        ),
    ]
