# Generated by Django 5.2.9 on 2025-12-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_alter_poipagegalleryimage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiindexpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poi_indexes', to='poi.poicategory'),
        ),
    ]
