# Generated by Django 5.2.9 on 2025-12-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0004_poiindexpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poicategory',
            name='slug',
        ),
    ]
