# Generated by Django 5.2.9 on 2025-12-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0005_remove_poicategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poicategory',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'POI Category', 'verbose_name_plural': 'POI Categories'},
        ),
    ]
